//! 4:2:2 chroma (`chroma_format_idc == 2`) coverage — issue #48.
//!
//! Fixtures are generated by `scripts/gen_422_fixtures.py` (x265 raw Annex-B
//! streams under `testdata/hevc422/`, heif-enc HEICs under
//! `testdata/features/`). The pure-Rust decoder has no 4:2:2 transform-tree
//! path, so until that lands it must refuse these streams up front rather than
//! return an `Ok` frame with out-of-range chroma (the 10-bit failure mode in
//! #48) or a CABAC-desync error a few CTBs in (the 8-bit one).

use heic::{DecoderConfig, HeicError, HevcError, PixelLayout};
use std::path::PathBuf;

fn fixture(rel: &str) -> Vec<u8> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("testdata")
        .join(rel);
    std::fs::read(&p).unwrap_or_else(|e| panic!("missing committed fixture {p:?}: {e}"))
}

fn assert_raw_rejected(rel: &str) {
    let data = fixture(rel);
    match heic::hevc::decode(&data) {
        Err(HevcError::Unsupported(msg)) => {
            assert!(
                msg.contains("4:2:2"),
                "{rel}: message should name 4:2:2, got {msg:?}"
            );
        }
        Err(other) => panic!("{rel}: expected Unsupported(4:2:2), got {other:?}"),
        Ok(frame) => panic!(
            "{rel}: expected Unsupported(4:2:2), but decode returned Ok ({}x{} chroma_format={})",
            frame.width, frame.height, frame.chroma_format
        ),
    }
}

fn assert_container_rejected(rel: &str) {
    let data = fixture(rel);
    match DecoderConfig::new().decode(&data, PixelLayout::Rgb8) {
        Err(e) => match e.error() {
            HeicError::HevcDecode(HevcError::Unsupported(msg)) => {
                assert!(
                    msg.contains("4:2:2"),
                    "{rel}: message should name 4:2:2, got {msg:?}"
                );
            }
            other => panic!("{rel}: expected HevcDecode(Unsupported(4:2:2)), got {other:?}"),
        },
        Ok(out) => panic!(
            "{rel}: expected Unsupported(4:2:2), but decode returned Ok ({}x{})",
            out.width, out.height
        ),
    }
}

#[test]
fn raw_422_8bit_lossless_is_rejected_up_front() {
    assert_raw_rejected("hevc422/x265_422_8bit_lossless.hevc");
}

/// The #48 "returns Ok with chroma 17x out of range" path.
#[test]
fn raw_422_10bit_lossless_is_rejected_up_front() {
    assert_raw_rejected("hevc422/x265_422_10bit_lossless.hevc");
}

#[test]
fn heic_422_8bit_is_rejected_up_front() {
    assert_container_rejected("features/yuv422.heic");
}

#[test]
fn heic_422_10bit_is_rejected_up_front() {
    assert_container_rejected("features/yuv422_10bit.heic");
}
