//! Per-feature decode coverage against the small `testdata/features/` fixtures.
//!
//! These fixtures (generated by `scripts/gen_feature_fixtures.py`, each < 20 KB)
//! exercise the container/decode feature paths the synthetic + uncompressed
//! corpora never reach: derived images (`grid` / `iden` / `iovl`), item-property
//! transforms (`irot` / `imir` / `clap`), auxiliary alpha, thumbnails,
//! monochrome (4:0:0), 10-bit, 4:4:4, nclx colour signalling, and EXIF / XMP.
//!
//! Per this project's "false positives are the highest-severity bug" rule, every
//! assertion checks REAL output — exact dimensions plus pixel content classified
//! by dominant colour, so a decoder that merely "accepts the bytes" but applies
//! the wrong transform (or none) fails here. The corner-colour goldens were
//! cross-checked pixel-for-pixel against libheif `heif-dec` 1.21.2 on 2026-05-31
//! (rust output == libheif output for every transform / iden / iovl fixture; the
//! 4:4:4 fixture matched libheif at MAE 1.4/65535). The corner layout of the
//! transform base image is TL=red TR=green BL=blue BR=yellow.

use heic::{DecoderConfig, HeicError, ImageInfo, PixelLayout};
use std::path::{Path, PathBuf};

fn features_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata")
        .join("features")
}

fn read(name: &str) -> Vec<u8> {
    let p = features_dir().join(name);
    std::fs::read(&p).unwrap_or_else(|e| panic!("missing committed fixture {p:?}: {e}"))
}

fn decode_rgb(name: &str) -> DecodeRgb {
    let data = read(name);
    let out = DecoderConfig::new()
        .decode(&data, PixelLayout::Rgb8)
        .unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));
    assert_eq!(out.layout, PixelLayout::Rgb8);
    assert_eq!(
        out.data.len(),
        out.width as usize * out.height as usize * 3,
        "{name}: rgb buffer size mismatch"
    );
    DecodeRgb {
        w: out.width,
        h: out.height,
        data: out.data,
    }
}

struct DecodeRgb {
    w: u32,
    h: u32,
    data: Vec<u8>,
}

impl DecodeRgb {
    fn px(&self, x: u32, y: u32) -> (u8, u8, u8) {
        let i = (y as usize * self.w as usize + x as usize) * 3;
        (self.data[i], self.data[i + 1], self.data[i + 2])
    }
    fn tl(&self) -> Color {
        classify(self.px(1, 1))
    }
    fn tr(&self) -> Color {
        classify(self.px(self.w - 2, 1))
    }
    fn bl(&self) -> Color {
        classify(self.px(1, self.h - 2))
    }
    fn br(&self) -> Color {
        classify(self.px(self.w - 2, self.h - 2))
    }
    fn center(&self) -> Color {
        classify(self.px(self.w / 2, self.h / 2))
    }
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
enum Color {
    Red,
    Green,
    Blue,
    Yellow,
    Black,
    White,
    Mixed,
}

fn classify((r, g, b): (u8, u8, u8)) -> Color {
    let (r, g, b) = (r as i32, g as i32, b as i32);
    match () {
        _ if r > 180 && g < 90 && b < 90 => Color::Red,
        _ if g > 180 && r < 90 && b < 90 => Color::Green,
        _ if b > 180 && r < 90 && g < 110 => Color::Blue,
        _ if r > 180 && g > 180 && b < 100 => Color::Yellow,
        _ if r < 45 && g < 45 && b < 45 => Color::Black,
        _ if r > 205 && g > 205 && b > 205 => Color::White,
        _ => Color::Mixed,
    }
}

// ---------------------------------------------------------------------------
// Baseline single image (heif-enc codes 64x64, clap-crops to 48x48 visible)
// ---------------------------------------------------------------------------
#[test]
fn single_image_clap_cropped_to_visible_size() {
    let d = decode_rgb("single.heic");
    // The coded image is 64x64 but a `clap` essential property crops it to the
    // 48x48 visible window — if clap weren't applied we'd see 64x64.
    assert_eq!((d.w, d.h), (48, 48), "clap clean-aperture not applied");
    // red->blue vertical gradient: top is red, bottom is blue.
    assert_eq!(d.tl(), Color::Red);
    assert_eq!(d.bl(), Color::Blue);
}

// ---------------------------------------------------------------------------
// Item-property transforms: irot / imir
// ---------------------------------------------------------------------------
#[test]
fn irot_90_rotates_and_swaps_dimensions() {
    let d = decode_rgb("irot90.heic");
    // base is 64x40; 90-degree rotation swaps to 40x64.
    assert_eq!((d.w, d.h), (40, 64), "irot90 did not swap dimensions");
    // base corners TL=red TR=green BL=blue BR=yellow -> after 90deg CCW:
    assert_eq!(d.tl(), Color::Green);
    assert_eq!(d.tr(), Color::Yellow);
    assert_eq!(d.bl(), Color::Red);
    assert_eq!(d.br(), Color::Blue);
}

#[test]
fn irot_270_rotates_and_swaps_dimensions() {
    let d = decode_rgb("irot270.heic");
    assert_eq!((d.w, d.h), (40, 64));
    assert_eq!(d.tl(), Color::Blue);
    assert_eq!(d.tr(), Color::Red);
    assert_eq!(d.bl(), Color::Yellow);
    assert_eq!(d.br(), Color::Green);
}

#[test]
fn imir_horizontal_axis_flips_left_right() {
    let d = decode_rgb("imir_h.heic");
    assert_eq!((d.w, d.h), (64, 40), "mirror must preserve dimensions");
    // left-right flip of TL=red TR=green BL=blue BR=yellow
    assert_eq!(d.tl(), Color::Green);
    assert_eq!(d.tr(), Color::Red);
    assert_eq!(d.bl(), Color::Yellow);
    assert_eq!(d.br(), Color::Blue);
}

#[test]
fn imir_vertical_axis_flips_top_bottom() {
    let d = decode_rgb("imir_v.heic");
    assert_eq!((d.w, d.h), (64, 40));
    // top-bottom flip
    assert_eq!(d.tl(), Color::Blue);
    assert_eq!(d.tr(), Color::Yellow);
    assert_eq!(d.bl(), Color::Red);
    assert_eq!(d.br(), Color::Green);
}

// ---------------------------------------------------------------------------
// Derived images: identity (iden) + overlay (iovl)
// ---------------------------------------------------------------------------
#[test]
fn iden_identity_derived_applies_own_rotation() {
    // iden item is primary, references a hidden coded image, carries its own
    // irot=90 property. Output must be the rotated source.
    let d = decode_rgb("iden_rot90.heic");
    assert_eq!((d.w, d.h), (64, 64));
    assert_eq!(d.tl(), Color::Green);
    assert_eq!(d.tr(), Color::Yellow);
    assert_eq!(d.bl(), Color::Red);
    assert_eq!(d.br(), Color::Blue);
}

#[test]
fn iovl_overlay_composites_onto_canvas_with_fill_and_offset() {
    // 64x64 image placed at offset (16,16) on a 96x96 canvas; fill is
    // transparent black. Canvas corners are untouched fill (black); the
    // canvas centre (48,48) falls inside the image's bottom-right (yellow).
    let d = decode_rgb("iovl.heic");
    assert_eq!((d.w, d.h), (96, 96), "overlay canvas size wrong");
    assert_eq!(d.tl(), Color::Black, "overlay fill not applied at corner");
    assert_eq!(d.br(), Color::Black);
    assert_eq!(d.center(), Color::Yellow, "overlay image not composited");
}

// ---------------------------------------------------------------------------
// Grid (derived 'grid' from 2x2 and 3x2 tiles)
// ---------------------------------------------------------------------------
#[test]
fn grid_2x2_assembles_full_image() {
    let d = decode_rgb("grid.heic");
    assert_eq!((d.w, d.h), (96, 96));
    // plasma content: just require the four quadrants aren't all identical
    // (a broken grid assembler tends to repeat one tile or leave a quadrant
    // blank).
    let q = [d.px(24, 24), d.px(72, 24), d.px(24, 72), d.px(72, 72)];
    assert!(
        q.iter().any(|&p| p != q[0]),
        "grid quadrants are all identical — tiles not placed"
    );
}

#[test]
fn grid_3x2_nokia_conformance_assembles() {
    let d = decode_rgb("nokia_grid3x2.heic");
    assert_eq!((d.w, d.h), (128, 72));
    let q = [d.px(20, 18), d.px(108, 18), d.px(64, 54)];
    assert!(q.iter().any(|&p| p != q[0]), "3x2 grid tiles not placed");
}

// ---------------------------------------------------------------------------
// Monochrome 4:0:0
// ---------------------------------------------------------------------------
#[test]
fn monochrome_400_decodes_to_gray() {
    let data = read("mono.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert_eq!(info.chroma_format, 0, "mono.heic should be 4:0:0");
    let d = decode_rgb("mono.heic");
    assert_eq!((d.w, d.h), (48, 48));
    // 4:0:0 -> R==G==B at every sample (no chroma). Tolerate +/-2 conversion.
    for &(x, y) in &[(1, 1), (24, 24), (46, 46), (1, 46)] {
        let (r, g, b) = d.px(x, y);
        let max = r.max(g).max(b) as i32;
        let min = r.min(g).min(b) as i32;
        assert!(
            max - min <= 3,
            "mono pixel not gray at ({x},{y}): {r},{g},{b}"
        );
    }
    // black->white gradient: top dark, bottom light.
    assert!(d.px(24, 1).0 < 60, "mono top should be dark");
    assert!(d.px(24, 46).0 > 200, "mono bottom should be light");
}

// ---------------------------------------------------------------------------
// 10-bit
// ---------------------------------------------------------------------------
#[test]
fn ten_bit_decodes_and_downconverts() {
    let data = read("depth10.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert_eq!(info.bit_depth, 10, "depth10.heic should report 10-bit");
    let d = decode_rgb("depth10.heic");
    assert_eq!((d.w, d.h), (64, 64));
    assert_eq!(d.tl(), Color::Red);
    assert_eq!(d.bl(), Color::Blue);
}

// ---------------------------------------------------------------------------
// 4:4:4 chroma (Nokia MIAF003, RExt)
// ---------------------------------------------------------------------------
#[test]
fn yuv444_decodes() {
    let data = read("nokia_444.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert_eq!(info.chroma_format, 3, "nokia_444 should be 4:4:4");
    let d = decode_rgb("nokia_444.heic");
    assert_eq!((d.w, d.h), (2048, 2048));
    // distinct coloured quadrants in the conformance pattern
    assert_ne!(d.tl(), d.br(), "4:4:4 quadrants should differ");
}

// ---------------------------------------------------------------------------
// Auxiliary alpha plane
// ---------------------------------------------------------------------------
#[test]
fn alpha_auxiliary_plane_is_decoded() {
    let data = read("alpha.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert!(info.has_alpha, "alpha.heic should report has_alpha");
    let out = DecoderConfig::new()
        .decode(&data, PixelLayout::Rgba8)
        .unwrap();
    assert_eq!(out.layout, PixelLayout::Rgba8);
    assert_eq!(out.data.len(), out.width as usize * out.height as usize * 4);
    // fixture encodes a uniform 50% alpha; assert it is neither fully opaque
    // nor fully transparent at a sampled pixel.
    let a = out.data[3];
    assert!(
        (20..235).contains(&a),
        "alpha plane not applied (got {a}, expected ~mid)"
    );
}

// ---------------------------------------------------------------------------
// Thumbnail
// ---------------------------------------------------------------------------
#[test]
fn thumbnail_is_present_and_decodes_small() {
    let data = read("thumb.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert!(info.has_thumbnail, "thumb.heic should report has_thumbnail");
    let thumb = DecoderConfig::new()
        .decode_thumbnail(&data, PixelLayout::Rgb8)
        .unwrap()
        .expect("thumbnail should decode");
    assert!(
        thumb.width <= 16 && thumb.width > 0,
        "thumb width {}",
        thumb.width
    );
    assert!(thumb.height <= 16 && thumb.height > 0);
    // primary is larger than the thumbnail
    let primary = decode_rgb("thumb.heic");
    assert!(primary.w > thumb.width, "primary should exceed thumbnail");
}

// ---------------------------------------------------------------------------
// nclx colour signalling (BT.709 vs BT.2020 PQ)
// ---------------------------------------------------------------------------
#[test]
fn nclx_color_signalling_is_read() {
    let bt709 = ImageInfo::from_bytes(&read("bt709.heic")).unwrap();
    assert_eq!(bt709.color_primaries, 1, "bt709 primaries");
    assert_eq!(bt709.transfer_characteristics, 1, "bt709 transfer");
    assert_eq!(bt709.matrix_coefficients, 1, "bt709 matrix");

    let bt2020 = ImageInfo::from_bytes(&read("bt2020pq.heic")).unwrap();
    assert_eq!(bt2020.color_primaries, 9, "bt2020 primaries");
    assert_eq!(bt2020.transfer_characteristics, 16, "bt2020 PQ transfer");
    assert_eq!(bt2020.matrix_coefficients, 9, "bt2020 matrix");

    // both still decode to the gradient
    assert_eq!(decode_rgb("bt709.heic").tl(), Color::Red);
    assert_eq!(decode_rgb("bt2020pq.heic").tl(), Color::Red);
}

// ---------------------------------------------------------------------------
// EXIF / XMP metadata items
// ---------------------------------------------------------------------------
#[test]
fn exif_metadata_extracted() {
    let data = read("exif.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert!(info.has_exif, "exif.heic should report has_exif");
    let exif = DecoderConfig::new()
        .extract_exif(&data)
        .unwrap()
        .expect("EXIF payload");
    // raw TIFF — the Make string we wrote appears verbatim.
    assert!(
        exif.windows(7).any(|w| w == b"ZenTest"),
        "EXIF Make string not found in payload"
    );
}

#[test]
fn xmp_metadata_extracted() {
    let data = read("xmp.heic");
    let info = ImageInfo::from_bytes(&data).unwrap();
    assert!(info.has_xmp, "xmp.heic should report has_xmp");
    let xmp = DecoderConfig::new()
        .extract_xmp(&data)
        .unwrap()
        .expect("XMP payload");
    assert!(
        xmp.windows(10).any(|w| w == b"zenfixture"),
        "XMP subject not found in payload"
    );
}

// ---------------------------------------------------------------------------
// Lossless (cu_transquant_bypass, 10-bit 4:4:4 intra-NxN, matrix=0 GBR).
// Decodes bit-exact vs libheif (verified via raw pixels) — a vertical
// red→blue gradient: top red, bottom blue, green ~0 throughout.
// ---------------------------------------------------------------------------
#[test]
fn lossless_decodes_gradient() {
    let d = decode_rgb("lossless.heic");
    assert_eq!((d.w, d.h), (48, 48));
    // top = red, bottom = blue (matrix=0 GBR: R=Cr plane, B=Cb plane).
    assert_eq!(d.tl(), Color::Red, "lossless top should be red");
    assert_eq!(d.tr(), Color::Red);
    assert_eq!(d.bl(), Color::Blue, "lossless bottom should be blue");
    assert_eq!(d.br(), Color::Blue);
    // green channel is ~0 everywhere (red↔blue gradient has no green).
    for &(x, y) in &[(1, 1), (24, 24), (46, 46), (1, 46)] {
        assert!(d.px(x, y).1 < 30, "green should be ~0 at ({x},{y})");
    }
}

// ---------------------------------------------------------------------------
// Overlay edge cases: 32-bit large format, negative offset, version reject,
// canvas-size limit. (mux'd by scripts/gen_feature_fixtures.py)
// ---------------------------------------------------------------------------
#[test]
fn iovl_large_format_32bit_matches_16bit() {
    // flags&1 selects 32-bit canvas/offset fields. Same geometry as iovl.heic,
    // so the output must be byte-identical to the 16-bit fixture.
    let big = DecoderConfig::new()
        .decode(&read("iovl_large.heic"), PixelLayout::Rgb8)
        .unwrap();
    let small = DecoderConfig::new()
        .decode(&read("iovl.heic"), PixelLayout::Rgb8)
        .unwrap();
    assert_eq!((big.width, big.height), (96, 96));
    assert_eq!(
        big.data, small.data,
        "32-bit overlay output must equal 16-bit overlay output"
    );
}

#[test]
fn iovl_negative_offset_clips_tile() {
    // Tile at (-16,-16) on a 96x96 canvas: canvas (0..48,0..48) shows tile
    // pixels (16..64,16..64); beyond x=48/y=48 is fill. This is the spec
    // src_skip path. (libheif skips negative-offset tiles entirely and fails
    // Nokia C021 — our compositing is the spec-compliant one; goldens are
    // spec-derived from the TL=red TR=green BL=blue BR=yellow tile layout.)
    let d = decode_rgb("iovl_negoff.heic");
    assert_eq!((d.w, d.h), (96, 96));
    assert_eq!(classify(d.px(10, 10)), Color::Red); // tile (26,26)
    assert_eq!(classify(d.px(40, 10)), Color::Green); // tile (56,26)
    assert_eq!(classify(d.px(10, 40)), Color::Blue); // tile (26,56)
    assert_eq!(classify(d.px(40, 40)), Color::Yellow); // tile (56,56)
    assert_eq!(
        classify(d.px(60, 60)),
        Color::Black,
        "past clip boundary = fill"
    );
    assert_eq!(classify(d.px(90, 90)), Color::Black);
}

#[test]
fn iovl_bad_version_is_unsupported() {
    let err = DecoderConfig::new()
        .decode(&read("iovl_badver.heic"), PixelLayout::Rgb8)
        .unwrap_err();
    assert!(
        matches!(err.error(), HeicError::Unsupported(_)),
        "overlay version!=0 should be Unsupported, got {:?}",
        err.error()
    );
}

#[test]
fn iovl_oversized_canvas_hits_limit() {
    // 40000x40000 canvas exceeds the default dimension limit and must be
    // rejected BEFORE any allocation (decode.rs check_dimensions, line 496).
    let err = DecoderConfig::new()
        .decode(&read("iovl_huge_canvas.heic"), PixelLayout::Rgb8)
        .unwrap_err();
    assert!(
        matches!(err.error(), HeicError::LimitExceeded(_)),
        "oversized overlay canvas should be LimitExceeded, got {:?}",
        err.error()
    );
}

// ---------------------------------------------------------------------------
// Derived-image recursion depth guard (MAX_DERIVED_DEPTH = 3)
// ---------------------------------------------------------------------------
#[test]
fn iden_chain_depth2_decodes() {
    // positive control: a 2-deep iden chain is within the limit.
    let d = decode_rgb("iden_depth2.heic");
    assert_eq!((d.w, d.h), (64, 64));
}

#[test]
fn iden_chain_depth4_is_rejected() {
    // 4 nested iden items exceed MAX_DERIVED_DEPTH and must error, not recurse
    // unboundedly (stack-safety on adversarial nesting).
    let err = DecoderConfig::new()
        .decode(&read("iden_depth4.heic"), PixelLayout::Rgb8)
        .unwrap_err();
    assert!(
        matches!(err.error(), HeicError::InvalidData(_)),
        "over-deep iden chain should be InvalidData, got {:?}",
        err.error()
    );
}
